# Generated by Django 5.2.7 on 2025-10-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наиманование товара",
                        max_length=100,
                        verbose_name="Имя товара",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание товара",
                        verbose_name="Описание товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наиманование товара",
                        max_length=100,
                        verbose_name="Имя товара",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание товара",
                        verbose_name="Описание товара",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото товара",
                        null=True,
                        upload_to="catalog/photo",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Введите категорию товара",
                        max_length=100,
                        verbose_name="Название категории товара",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        help_text="Введите цену за товар", verbose_name="Цена товара"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        help_text="Введите дату создания товара",
                        verbose_name="Дата создания товара",
                    ),
                ),
                (
                    "updated_to",
                    models.DateField(
                        help_text="Введите дату последнего изменения товара",
                        verbose_name="Дата последнего изменения товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["name", "category"],
            },
        ),
    ]
